actions:
  - procedure: paru.install
    info: Installing zsh
    package: ["zsh"]

  - procedure: os.symlink
    info: Adding symlink to zsh config
    src: "./files/.zshrc"
    dst: "{{ user.home }}/.zshrc"

  - procedure: shell.run
    info: "Changing shell for user"
    command: chsh
    args: ["-s", "zsh"]
