actions:
  - procedure: paru.install
    info: Installing dolphin file manager
    package:
      - dolphin
      - dolphin-plugins
      - kio-admin
      - kompare
      - ffmpegthumbs
      - icoutils
      - kdegraphics-thumbnailers
      - kdesdk-thumbnailers
      - libappimage
      - qt6-imageformats
      - raw-thumbnailer
      - resvg
      - taglib
